site_name: Host Mobility Documentation

theme:
  name: material
  logo: assets/hm-logo-grey-on-transparent.svg

nav:
  - index.md
  - tags.md

plugins:
  - search:
  - tags:
      tags_file: tags.md
  - plantuml:
      puml_url: http://anansi.setekgroup.local:8081
